### ISSUE TITLE
Rope Javelin stacking & quiver

### ISSUE THREAD

**Issue by Inqie** [Lyeoj/TerraFirmaThings#2]
If Javelins are in a stack in the hotbar, and you use it (LMB or RMB), all javelins in that stack gain damage rather than just one. If the player isn't paying attention, this could result in wasting the other javelins (particularly bad if they're made from expensive alloys). This isn't a bug, and probably just an oversight. 

In addition, you can't place rope javelins in the TFC Quiver like you can with normal javelins. This becomes a problem, especially with the stacking issue, if you're like me and never want to be caught without a weapon.

I'd suggest forcing them to be unstacked like most tools (or auto-unstack when used) and making them quiver-compatible.

**Comment by Lyeoj** [comment]
Whoops, the issue here is actually that rope javelins aren't supposed to stack at all! When it comes to quiver compatibility, I intended for them to not be used with quivers, since there is no reason to carry a bunch when you can just pull one back! I know the durability on javelins isn't that great, but actually behind the scenes, rope javelins use their durability just a bit more efficiently than regular javelins (regular javelins can take up to 5 damage (randomly) when hitting an entity while rope ones will only take 2 damage when hitting one). 
The fix I will implement in the next release will be to remove the stacking from the javelins. If there is still a strong enough desire to use them with a quiver, I may reconsider that for a future release, but implementing them to work with a quiver may require a large amount of extra effort.

**Comment by Lyeoj** [comment]
Addressed in Release 0.8.0
